# Generated by Django 3.2.13 on 2022-04-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataURI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURI', models.TextField()),
            ],
        ),
    ]
